# Generated by Django 6.1 on 2026-08-22 20:20

import faq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('icon', models.ImageField(upload_to=faq.models.path_to_faq_categories_icons)),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order',),
            },
        ),
    ]
