# Generated by Django 6.1 on 2026-08-22 20:25

import faq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfaq',
            name='icon',
            field=models.FileField(upload_to=faq.models.path_to_faq_categories_icons, verbose_name='Иконка'),
        ),
    ]
