# Generated by Django 6.1 on 2026-08-22 20:40

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_categoryfaq_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfaq',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.CreateModel(
            name='QuestionFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ответ')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('category_faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.categoryfaq', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
                'ordering': ('order',),
            },
        ),
    ]
