# Generated by Django 6.1 on 2026-08-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_categoryfaq_order_questionfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfaq',
            name='category_faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='faq.categoryfaq', verbose_name='Категория'),
        ),
    ]
