# Generated by Django 6.1 on 2026-09-21 10:12

import ckeditor_uploader.fields
import instructions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ответ')),
                ('block', models.CharField(choices=[('block_1', 'Блок 1'), ('mistakes', 'Распространенные ошибки'), ('block_2', 'Блок 2')], default='block_1', max_length=100, verbose_name='Блок отображения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Совет',
                'verbose_name_plural': 'Советы эксперта',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='InstructionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to=instructions.models.path_to_images_instruction, verbose_name='Картинка')),
                ('text_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='QuestionInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ответ')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
                'ordering': ('order',),
            },
        ),
    ]
