# Generated by Django 6.1 on 2026-09-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructioncard',
            old_name='icon',
            new_name='image',
        ),
    ]
