# Generated by Django 6.1 on 2026-09-21 15:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_rename_icon_instructioncard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertadvice',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
    ]
