# Generated by Django 6.1 on 2026-08-23 19:19

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(default=0, upload_to=catalog.models.path_to_category_cover, verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
