# Generated by Django 6.1 on 2026-08-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='animation',
            field=models.IntegerField(blank=True, default=0, verbose_name='Анимация загрузки (м.сек)'),
        ),
    ]
