# Generated by Django 6.1 on 2026-08-23 19:54

import catalog.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_animation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('cover', models.ImageField(upload_to=catalog.models.path_to_category_cover, verbose_name='Обложка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('animation', models.IntegerField(blank=True, default=0, verbose_name='Анимация загрузки (м.сек)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
                'ordering': ['order'],
            },
        ),
    ]
