# Generated by Django 6.1 on 2026-08-24 16:25

import catalog.models
import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('cover_1', models.ImageField(upload_to=catalog.models.path_to_product_images, verbose_name='Обложка 1')),
                ('cover_2', models.ImageField(upload_to=catalog.models.path_to_product_images, verbose_name='Обложка 2')),
                ('video', models.FileField(blank=True, upload_to=catalog.models.path_to_product_images, verbose_name='Видео')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость (₸)')),
                ('type', models.CharField(choices=[('product', 'Обычный продукт'), ('combo', 'Комбо-набор'), ('accessories', 'Аксессуар')], default='text', max_length=100, verbose_name='Шаблон')),
                ('text_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('text_2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('text_3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Как оплатить')),
                ('text_4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Покупка и возврат')),
                ('text_5', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='FAQ')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('popular', models.BooleanField(default=False, verbose_name='Популярный?')),
                ('new', models.BooleanField(default=False, verbose_name='Новинка?')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('style', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.style', verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
