# Generated by Django 6.1 on 2026-08-24 21:16

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_1',
            field=models.ImageField(upload_to=catalog.models.path_to_product_images, verbose_name='Картинка 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_2',
            field=models.ImageField(upload_to=catalog.models.path_to_product_images, verbose_name='Картинка 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('product', 'Обычный продукт'), ('combo', 'Комбо-набор'), ('accessories', 'Аксессуар')], default='product', max_length=100, verbose_name='Тип товара'),
        ),
    ]
