# Generated by Django 6.1 on 2026-08-25 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_accessoriescategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acessories',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.accessoriescategory', verbose_name='Категория аксессура'),
            preserve_default=False,
        ),
    ]
