# Generated by Django 6.1 on 2026-09-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='acessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.accessoriescategory', verbose_name='Категория аксессура'),
        ),
    ]
