# Generated by Django 6.1 on 2026-08-20 19:25

import ckeditor_uploader.fields
import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('type', models.CharField(choices=[('text', 'Текстовая'), ('catalog', 'Каталог'), ('about', 'О компании'), ('reviews', 'Отзывы'), ('contacts', 'Контакты'), ('career', 'Карьера'), ('faq', 'FAQ')], default='text', max_length=100, verbose_name='Шаблон страницы')),
                ('text_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст 1')),
                ('image_1', models.ImageField(blank=True, upload_to=content.models.path_to_pages_images, verbose_name='Картинка 1')),
                ('text_2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст 2')),
                ('image_2', models.ImageField(blank=True, upload_to=content.models.path_to_pages_images, verbose_name='Картинка 2')),
                ('text_3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст 3')),
                ('image_3', models.ImageField(blank=True, upload_to=content.models.path_to_pages_images, verbose_name='Картинка 3')),
                ('keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('is_dedicated', models.BooleanField(default=False, verbose_name='Выделенный пункт?')),
                ('header_menu', models.BooleanField(default=False, verbose_name='Отображать в основном меню?')),
                ('footer_menu', models.BooleanField(default=False, verbose_name='Отображать в подвале?')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ('order',),
            },
        ),
    ]
