# Generated by Django 6.1 on 2026-08-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='place_1',
            field=models.BooleanField(default=False, verbose_name='Header'),
        ),
        migrations.AddField(
            model_name='page',
            name='place_2',
            field=models.BooleanField(default=False, verbose_name='Footer 1'),
        ),
        migrations.AddField(
            model_name='page',
            name='place_3',
            field=models.BooleanField(default=False, verbose_name='Footer 2'),
        ),
        migrations.AddField(
            model_name='page',
            name='place_4',
            field=models.BooleanField(default=False, verbose_name='Footer 3'),
        ),
    ]
