# Generated by Django 6.1 on 2026-08-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_page_place_1_page_place_2_page_place_3_page_place_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовая'), ('catalog', 'Каталог'), ('about', 'О компании'), ('reviews', 'Отзывы'), ('contacts', 'Контакты'), ('career', 'Карьера'), ('faq', 'FAQ')], default='text', max_length=100, verbose_name='Шаблон'),
        ),
    ]
