# Generated by Django 6.1 on 2026-08-22 21:18

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_socialnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('icon', models.FileField(upload_to=content.models.path_to_icons_payment_methods, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Метод оплаты',
                'verbose_name_plural': 'Методы оплаты',
                'ordering': ('order',),
            },
        ),
    ]
