# Generated by Django 6.1 on 2026-08-22 21:54

import ckeditor_uploader.fields
import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('photo_client', models.ImageField(upload_to=content.models.path_to_review_photos, verbose_name='Фото клиента')),
                ('review', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст отзыва')),
                ('photo_review', models.ImageField(upload_to=content.models.path_to_review_photos, verbose_name='Фото отзыва')),
                ('published_at', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-published_at',),
            },
        ),
    ]
