# Generated by Django 6.1 on 2026-08-22 22:32

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('icon', models.FileField(upload_to=content.models.path_to_icons_benefits, verbose_name='Иконка')),
                ('animation', models.IntegerField(blank=True, default=0, verbose_name='Задержка появления (м.сек)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ('order',),
            },
        ),
    ]
