# Generated by Django 6.1 on 2026-08-23 17:30

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_benefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to=content.models.path_to_about_images, verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'О компании',
            },
        ),
    ]
