# Generated by Django 6.1 on 2026-08-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_abouthome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouthome',
            options={'verbose_name': 'О компании на главной'},
        ),
    ]
