# Generated by Django 6.1 on 2026-08-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_abouthome_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouthome',
            options={'verbose_name': 'О компании на главной', 'verbose_name_plural': 'О компании на главной'},
        ),
    ]
