# Generated by Django 6.1 on 2026-08-25 18:24

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_abouthome_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to=content.models.path_to_slider_images, verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_on_button', models.CharField(max_length=255, verbose_name='Текст на кнопке')),
                ('link_on_button', models.CharField(max_length=500, verbose_name='Ссылка на кнопке')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайдер',
                'ordering': ('order',),
            },
        ),
    ]
