# Generated by Django 6.1 on 2026-09-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовая'), ('catalog', 'Каталог'), ('about', 'О компании'), ('reviews', 'Отзывы'), ('contacts', 'Контакты'), ('career', 'Карьера'), ('faq', 'FAQ'), ('instructions', 'Инструкции'), ('materials', 'Материалы')], default='text', max_length=100, verbose_name='Шаблон'),
        ),
    ]
